trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default' #self hosted agent pool

variables:
# Azure DevOps service connection name
 - name: azureSubscription
   value: AzureBluecorpConnection
# Resource group
 - name: resourceGroup
   value: 'bluecorp_service_rg'
# Azure region to deploy resources to
 - name: location
   value: 'australiaeast'
# Function app name
 - name: functionAppName
   value: 'bluecorp-order-service'
#Function app folder
 - name: functionAppFolder
   value: '.'  # Root folder where function.py and requirements.txt are located


stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Bicep Template'
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy to Azure'
        steps:
          # Step 1: Set python path
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11.9'
            displayName: 'Set python path and validate'

          # Step 2: Validate Azure CLI Installation
          - script: |
              az --version
            displayName: 'Validate Azure CLI Installation'

          # Step 3: Log in to Azure and show account
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal --username ${env:AZURESERVICEPRINCIPALUSERNAME} --password=${env:AZURESERVICEPRINCIPALPASSWORD} --tenant ${env:TENANTID}
                az account show
                az account set --subscription ${env:AZURESUBSCRIPTIONID}
                az group create --name ${env:resourceGroup} --location ${env:location}
            displayName: 'Log in to Azure using service principal'

          # Step 4: Deploy the Bicep template to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create `
                  --resource-group ${env:resourceGroup} `
                  --template-file infrastructure/azure_template.bicep `
                  --parameters location=${env:location}
            displayName: 'Deploy Bicep template to Azure'
          
          # Step 5: Set up Function App Environment
          - script: |
              python -m venv .venv
              if exist .venv\Scripts\activate (
                call .venv\Scripts\activate
              ) else (
                source .venv/bin/activate
              )
              python --version
              pip install --upgrade pip
              pip install -r $(functionAppFolder)/requirements.txt
            displayName: 'Set Up Python Virtual Environment and Install Dependencies'

          # Step 6: Install Azure Functions Core Tools and Publish function app to Azure
          - script: |
              npm install -g azure-functions-core-tools@4 --unsafe-perm true
              func --version
            #func azure functionapp publish $(functionAppName) --nozip
            displayName: 'Install Azure Functions Core Tools'

          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)'  # Root directory of your code
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/package.zip'
              replaceExistingArchive: true
            displayName: 'Create deployment package (ZIP)'
            
          - task: AzureFunctionApp@1
            inputs:
              azureSubscription: $(azureSubscription)  # Replace with your Azure subscription
              appType: 'functionAppLinux'
              appName: $(functionAppName)
              package: '$(Build.ArtifactStagingDirectory)/package.zip'
              deploymentMethod: 'zipDeploy'
            displayName: 'Deploy Function App code'
            
          # Step 7: Post-deployment steps (optional, e.g., notifications, tests)

