trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default' #self hosted agent pool

#variables:
# Azure DevOps service connection name
# - name: azureSubscription
#   value: AzureBluecorpConnection
# Resource group
# - name: resourceGroup
#   value: 'bluecorp_service_rg'
# Azure region to deploy resources to
# - name: location
#   value : 'australiaeast'

stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Bicep Template'
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy to Azure'
        steps:
          # Step 1: Set python path
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11.9'
            displayName: 'Set python path and validate'
          
          # Step 2: Install Azure CLI on Windows
          #- script: |
          #    powershell -Command "& {Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile AzureCLI.msi; Start-Process msiexec.exe -ArgumentList '/I AzureCLI.msi /quiet' -Wait; Remove-Item AzureCLI.msi}"
          #  displayName: 'Install Azure CLI'

          # Step 3: Validate Azure CLI Installation
          - script: |
              az --version
            displayName: 'Validate Azure CLI Installation'

          # Install Azure CLI 
          #- script: |
          #    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          #    sudo apt-get install azure-cli
          #  displayName: 'Install Azure CLI'

          # Step 4: Log in to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: "AzureBluecorpConnection"
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal --username ${env:AZURESERVICEPRINCIPALUSERNAME} --password=${env:AZURESERVICEPRINCIPALPASSWORD} --tenant ${env:TENANTID}
                az account set --subscription ${env:TENANTID}
            displayName: 'Log in to Azure using service principal'

          # Step 5: Deploy the Bicep template to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: "AzureBluecorpConnection"
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create `
                  --resource-group bluecorp_service_rg `
                  --template-file infrastructure/azure_template.bicep `
                  --parameters location="australiaeast"
            displayName: 'Deploy Bicep template to Azure'

          # Step 6: Post-deployment steps (optional, e.g., notifications, tests)

