trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  name: 'Default' #self hosted agent pool

variables:
# Azure DevOps service connection name
 - name: azureSubscription
   value: AzureBluecorpConnection
# Resource group
 - name: resourceGroup
   value: 'bluecorp_service_rg'
# Azure region to deploy resources to
 - name: location
   value: 'australiaeast'
# Function app name
 - name: functionAppName
   value: dispatch-order
#Function app folder
 - name: functionAppFolder
   value: .  # Root folder where function.py and requirements.txt are located


stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Bicep Template'
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy to Azure'
        steps:
          # Step 1: Set python path
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.11.9'
            displayName: 'Set python path and validate'

          # Step 2: Validate Azure CLI Installation
          - script: |
              az --version
            displayName: 'Validate Azure CLI Installation'

          # Step 3: Log in to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal --username ${env:AZURESERVICEPRINCIPALUSERNAME} --password=${env:AZURESERVICEPRINCIPALPASSWORD} --tenant ${env:TENANTID}
                az account set --subscription ${env:AZURESUBSCRIPTIONID}
            displayName: 'Log in to Azure using service principal'

          # Step 4: Deploy the Bicep template to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'ps'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create `
                  --resource-group ${env:resourceGroup} `
                  --template-file infrastructure/azure_template.bicep `
                  --parameters location=${env:location}
            displayName: 'Deploy Bicep template to Azure'
          
          # Step 5: Set up Function App Environment
          - script: |
              python -m venv .venv
              source .venv/Scripts/activate
              python --version
              pip install --upgrade pip
              pip install -r $(functionAppFolder)/requirements.txt || echo "Failed to install dependencies"
            displayName: 'Set up Function App Environment'

          # Step 6: Publish Python Function App
          - script: |
              func azure functionapp publish $(functionAppName) --nozip --python
            displayName: 'Publish Python Function App to Azure'

          # Step 6: Post-deployment steps (optional, e.g., notifications, tests)

