trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for running the pipeline

variables:
  azureSubscription: 'AzureBluecorpConnection'  # Your Azure DevOps service connection name
  resourceGroup: 'bluecorp_service_rg'  # Name of your new resource group
  location: 'australiaeast'  # Azure region to deploy resources to

stages:
  - stage: BuildAndDeploy
    displayName: 'Build and Deploy Bicep Template'
    jobs:
      - job: DeployToAzure
        displayName: 'Deploy to Azure'
        steps:
          # Step 1: Checkout your code from GitHub
          - task: Checkout@1

          # Step 2: Install Azure CLI
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'

          - script: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              sudo apt-get install azure-cli
            displayName: 'Install Azure CLI'

          # Step 3: Log in to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login --service-principal -u $(azureServicePrincipalUsername) -p $(azureServicePrincipalPassword) --tenant $(tenantId)
                az account set --subscription $(azureSubscription)

          # Step 4: Deploy the Bicep template to Azure
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --template-file infrastructure/azure_template.bicep

          # Step 5: Post-deployment steps (optional, e.g., notifications, tests)
